In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/SEM 7/MACHINE LEARNING II/Coffe_sales.csv")

**Menghitung total penjualan per kategori minuman**

In [ ]:
print("\nTanggal awal:", df["Date"].min())
print("Tanggal akhir:", df["Date"].max())

print("\nJumlah catatan per jenis kopi:")
print(
    df["coffee_name"]
    .value_counts()
)

Tanggal awal: 2024-03-01
Tanggal akhir: 2025-03-23

Jumlah catatan per jenis kopi:
coffee_name
Americano with Milk    809
Latte                  757
Americano              564
Cappuccino             486
Cortado                287
Hot Chocolate          276
Cocoa                  239
Espresso               129
Name: count, dtype: int64

**Menghitung penjualan keseluruhan per hari**

In [ ]:
penjualan_harian = (
    df.groupby('Date')
    .size()
    .reset_index(name='Jumlah Penjualan')
)

penjualan_harian.head(10)

         Date  Jumlah Penjualan
0  2024-03-01                11
1  2024-03-02                 6
2  2024-03-03                 9
3  2024-03-04                 4
4  2024-03-05                 9
5  2024-03-06                 4
6  2024-03-07                 4
7  2024-03-08                 8
8  2024-03-09                13
9  2024-03-10                 3

In [ ]:
count = len(penjualan_harian)
print(count)

381

**Menghitung jumlah penjualan per tanggal dan kategori waktu**

In [ ]:
penjualan_waktu = (
    df.groupby(['Date', 'Time_of_Day'])
    .size()
    .reset_index(name='Jumlah Penjualan')
    .sort_values(['Date', 'Time_of_Day'])
)

display(penjualan_waktu.head(20))

          Date Time_of_Day  Jumlah Penjualan
0   2024-03-01   Afternoon                 6
1   2024-03-01     Morning                 1
2   2024-03-01       Night                 4
3   2024-03-02   Afternoon                 2
4   2024-03-02     Morning                 3
5   2024-03-02       Night                 1
6   2024-03-03   Afternoon                 2
7   2024-03-03     Morning                 2
8   2024-03-03       Night                 5
9   2024-03-04   Afternoon                 1
10  2024-03-04     Morning                 3
11  2024-03-05   Afternoon                 1
12  2024-03-05     Morning                 1
13  2024-03-05       Night                 7
14  2024-03-06   Afternoon                 4
15  2024-03-07   Afternoon                 2
16  2024-03-07     Morning                 2
17  2024-03-08   Afternoon                 5
18  2024-03-08     Morning                 1
19  2024-03-08       Night                 2

Menghitung jumlah penjualan berdasarkan tanggal, hari, dan waktu

In [ ]:
penjualan_harian_waktu = (
    df.groupby(['Date', 'Weekday', 'Time_of_Day'])
    .size()
    .reset_index(name='Jumlah_Penjualan')
    .sort_values(['Date', 'Time_of_Day'])
    .reset_index(drop=True)
)

display(penjualan_harian_waktu)

           Date Weekday Time_of_Day  Jumlah_Penjualan
0    2024-03-01     Fri   Afternoon                 6
1    2024-03-01     Fri     Morning                 1
2    2024-03-01     Fri       Night                 4
3    2024-03-02     Sat   Afternoon                 2
4    2024-03-02     Sat     Morning                 3
..          ...     ...         ...               ...
951  2025-03-22     Sat     Morning                 4
952  2025-03-22     Sat       Night                 2
953  2025-03-23     Sun   Afternoon                 3
954  2025-03-23     Sun     Morning                 2
955  2025-03-23     Sun       Night                 1

[956 rows x 4 columns]

**Data Time Series per Kategori Waktu**

In [ ]:
import pandas as pd

df['Date'] = pd.to_datetime(df['Date'])

semua_tanggal = pd.date_range(
    start=df['Date'].min(),
    end=df['Date'].max(),
    freq='D'
)

kategori_waktu = ['Morning', 'Afternoon','Night']

data_per_waktu = {}

for waktu in kategori_waktu:
    data = (
        df[df['Time_of_Day'] == waktu]
        .groupby('Date')
        .size()
        .reindex(semua_tanggal, fill_value=0)
        .rename_axis('ds')
        .reset_index(name='y')
    )

    data_per_waktu[waktu] = data

# Contoh melihat data Night
display(data_per_waktu['Night'].head())

          ds  y
0 2024-03-01  4
1 2024-03-02  1
2 2024-03-03  5
3 2024-03-04  0
4 2024-03-05  7

**Penjualan menu tertinggi per hari**

In [ ]:
americano_harian = (
    df[df['coffee_name'] == 'Americano with Milk']
    .groupby('Date')
    .size()
    .reset_index(name='Jumlah Penjualan')
    .sort_values('Date')
)

americano_harian

          Date  Jumlah Penjualan
0   2024-03-01                 4
1   2024-03-02                 3
2   2024-03-03                 2
3   2024-03-04                 1
4   2024-03-07                 1
..         ...               ...
305 2025-03-18                 3
306 2025-03-19                 2
307 2025-03-20                 3
308 2025-03-21                 2
309 2025-03-22                 6

[310 rows x 2 columns]